# Generated by Django 6.0.5 on 2026-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pagado', models.BooleanField(default=False)),
                ('equipo_1', models.CharField(max_length=100)),
                ('equipo_2', models.CharField(max_length=100)),
                ('equipo_3', models.CharField(max_length=100)),
                ('equipo_4', models.CharField(max_length=100)),
                ('equipo_5', models.CharField(max_length=100)),
                ('equipo_6', models.CharField(max_length=100)),
                ('equipo_7', models.CharField(max_length=100)),
                ('equipo_8', models.CharField(max_length=100)),
                ('equipo_9', models.CharField(max_length=100)),
                ('equipo_10', models.CharField(max_length=100)),
                ('equipo_11', models.CharField(max_length=100)),
                ('equipo_12', models.CharField(max_length=100)),
                ('goleador', models.CharField(max_length=100)),
                ('equipo_goleador', models.CharField(max_length=100)),
                ('validacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
