# Generated by Django 6.0.5 on 2026-05-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('J1', 'Jornada 1'), ('J2', 'Jornada 2'), ('J3', 'Jornada 3'), ('1/16', '1/16 de final'), ('1/8', '1/8 de final'), ('1/4', '1/4 de final'), ('1/2', '1/2 de final'), ('FINAL', 'Final')], max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoleadorPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('goles', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores', to='apuestas.partido')),
            ],
        ),
    ]
