# Generated by Django 6.0.5 on 2026-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_partido_goleadorpartido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='orden',
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_partido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
