# Generated by Django 6.0.5 on 2026-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0003_remove_partido_orden_partido_fecha_partido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
