# Generated by Django 6.0.5 on 2026-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0004_alter_partido_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoleadorTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('jugador', 'equipo')},
            },
        ),
    ]
